version: "3"
services:
    api:
        build:
            context: .
            dockerfile: flask_conda.dockerfile
        image: test_flask_image 
        ports:
                - "9999:9998"
        restart: always
        volumes:
            - "./workspace:/app/dev_fileserver/dev_fileserver/workspace"